#!/bin/sh

export WINEPREFIX="$STEAM_COMPAT_DATA_PATH/pfx"

mkdir -p "$STEAM_COMPAT_DATA_PATH/pfx/drive_c/Program Files (x86)/Steam/"

for file in steamclient.dll steamclient64.dll; do
    cp "$STEAM_COMPAT_CLIENT_INSTALL_PATH/$file" "$STEAM_COMPAT_DATA_PATH/pfx/drive_c/Program Files (x86)/Steam/"
done

if [ "$1" != "waitforexitandrun" ]; then
    echo "Unknown verb $1."
    exit 1
fi
shift

dir="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)"

"$dir/wine/wine" "$@" > $HOME/raw-wine.log 2>&1
