name: Snapshot

on:
  workflow_dispatch:
  push:
    branches:
      - 'cachyos_*_*/main'
      - 'cachyos_*_*/dev'

concurrency:
  group: ${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  version:
    name: Version
    runs-on: ubuntu-latest
    outputs:
      tag_abbrev: ${{ steps.version.outputs.tag_abbrev }}
      tag_offset: ${{ steps.version.outputs.tag_offset }}
      sha_short: ${{ steps.version.outputs.sha_short }}
      full_desc: ${{ steps.version.outputs.full_desc }}
      branch: ${{ steps.version.outputs.branch }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        fetch-tags: true

    - name: Version
      id: version
      shell: bash
      run: |
        tag_abbrev=$(git describe --tags --abbrev=0)
        echo "tag_abbrev=$tag_abbrev" >> $GITHUB_OUTPUT
        echo "tag_offset=$(git rev-list $tag_abbrev..HEAD --count)" >> $GITHUB_OUTPUT
        echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
        echo "full_desc=$(git describe --long --tags)" >> $GITHUB_OUTPUT
        echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT

  build:
    name: Build
    needs: version
    runs-on: ubuntu-latest
    container:
      image: nellokudo/wine-builder:latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build
        run: |
          chmod +x .github/workflows/build.sh
          .github/workflows/build.sh

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: wine-cachyos-${{ needs.version.outputs.full_desc }}
          path: '*.tar.xz'
          if-no-files-found: error
